### PR TITLE
Feature/GitHub comments

### PR DESCRIPTION
**Pull request by EstebanDalelR**
## Description
Fixed Comments for gh (gl and bb untested)
## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)  
- [ ] New feature (non-breaking change which adds functionality)  
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)  
- [ ] Documentation update  
- [ ] Chore: cleanup/renaming, etc  
- [ ] RFC  
## Notes

Screenshot 2023-02-01 at 1 13 26 PM

## Acceptance

- [x] I have read [the Contributing guidelines](CONTRIBUTING.md)
- [x] I have read the [Code of Conduct](CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by baristaGeek** [comment]
Not sure if related but I got this error. Will dig deeper. 

Screen Shot 2023-02-01 at 3 53 35 PM

**Comment by baristaGeek** [comment]
> > Not sure if related but I got this error. Will dig deeper.
> > Screen Shot 2023-02-01 at 3 53 35 PM
> 
> I thought it was me. I think an API is down?
Screen Shot 2023-02-02 at 5 36 38 PM


I'm getting a different error now. Anyway... it looks like a validation error of some sort.

**Comment by baristaGeek** [comment]
There's an error on this PR which is the one that returns `cannot read properties of undefined (reading 'toString')`. Steps to replicate: 

get code context for pages/billing/index.tsx on our private repo, highlight the whole file and get code context
- If you do it with what we have on the dev branch it works
- If you do it on this branch, the error above is returned 

NOTE: The validation error I got on the turborepo repo is another error

**Review by baristaGeek — CHANGES_REQUESTED** [review]
Please solve the `cannot read properties of undefined (reading 'toString')` described on the PR conversation

**Comment by EstebanDalelR** [comment]
Cannot reproduce.
https://user-images.githubusercontent.com/11527621/216685548-ff668b8d-913c-4200-b500-6ea65a3a41c8.mov

**Comment by EstebanDalelR** [comment]
> Please solve the `cannot read properties of undefined (reading 'toString')` described on the PR conversation

Did you read the code?
No changes on anything that contains "toString" up to that point (https://github.com/watermelontools/watermelon-extension/pull/492/commits/4817e58e9a3db815f1bdcd37bc5c6de1c5db2a6c).
Something else but Ok.

**Comment by baristaGeek** [comment]
> > Please solve the `cannot read properties of undefined (reading 'toString')` described on the PR conversation
> 
> Did you read the code? No changes on anything that contains "toString" up to that point ([4817e58](https://github.com/watermelontools/watermelon-extension/commit/4817e58e9a3db815f1bdcd37bc5c6de1c5db2a6c)). Something else but Ok.

TBH I didn't at detail, but if it works on dev on the exact same file and block of code and not here, that's something to deal with

**Review by baristaGeek — APPROVED** [review]
LGMT now

**Pull request merged**
