### PR TITLE
Feature/jira comments

### PR DESCRIPTION
**Pull request by EstebanDalelR**
## Description
Fixes comment display
## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)  
- [ ] New feature (non-breaking change which adds functionality)  
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)  
- [ ] Documentation update  
- [ ] Chore: cleanup/renaming, etc  
- [ ] RFC  
## Acceptance

- [x] I have read [the Contributing guidelines](CONTRIBUTING.md)
- [x] I have read the [Code of Conduct](CODE_OF_CONDUCT.md)

### CODE REVIEW

**Review by baristaGeek — CHANGES_REQUESTED** [review]
Please remove the html tags on the comments

Screen Shot 2023-02-01 at 3 46 58 PM

**Comment by EstebanDalelR** [comment]
> Please remove the html tags on the comments
> 
> Screen Shot 2023-02-01 at 3 46 58 PM

Care to translate? It's either that or the array of blocks it sends.

**Comment by baristaGeek** [comment]
> > Please remove the html tags on the comments
> > Screen Shot 2023-02-01 at 3 46 58 PM
> 
> Care to translate? It's either that or the array of blocks it sends.

I will gladly "translate": 

Jira comments are inside the nested children objects shown in the image below. Once you dig deep, you get to the 'label' and 'tooltip' props that contain the comment, which contain those <p> tags, which we don't need on the text and take up space. 

My feedback is that we should remove them. If it comes like that from the endpoint, we could perhaps run a regex that cleans <p> tags. 

Screen Shot 2023-02-02 at 6 04 40 PM

**Comment by EstebanDalelR** [comment]
> > > Please remove the html tags on the comments
> 
> > > Screen Shot 2023-02-01 at 3 46 58 PM
> 
> > 
> 
> > Care to translate? It's either that or the array of blocks it sends.
> 
> 
> 
> I will gladly "translate": 
> 
> 
> 
> Jira comments are inside the nested children objects shown in the image below. Once you dig deep, you get to the 'label' and 'tooltip' props that contain the comment, which contain those <p> tags, which we don't need on the text and take up space. 
> 
> 
> 
> My feedback is that we should remove them. If it comes like that from the endpoint, we could perhaps run a regex that cleans <p> tags. 
> 
> 
> 
> Screen Shot 2023-02-02 at 6 04 40 PM
> 
> 

Won't fix. HTML is a great way to display. That's the PR I'm working on for VSCode. And markdown.

**Comment by baristaGeek** [comment]
> > > > Please remove the html tags on the comments
> > 
> > 
> > > > Screen Shot 2023-02-01 at 3 46 58 PM
> > 
> > 
> > > 
> > 
> > 
> > > Care to translate? It's either that or the array of blocks it sends.
> > 
> > 
> > I will gladly "translate":
> > Jira comments are inside the nested children objects shown in the image below. Once you dig deep, you get to the 'label' and 'tooltip' props that contain the comment, which contain those  tags, which we don't need on the text and take up space.
> > My feedback is that we should remove them. If it comes like that from the endpoint, we could perhaps run a regex that cleans  tags.
> > Screen Shot 2023-02-02 at 6 04 40 PM
> 
> Won't fix. HTML is a great way to display. That's the PR I'm working on for VSCode. And markdown.

Ok. Thanks for clarifying that it's related to the contribution to the VS Code repo

**Review by baristaGeek — APPROVED** [review]

**Pull request merged**
