### PR TITLE
Move Repo Starring to API

### PR DESCRIPTION
**Pull request by EstebanDalelR**
## Description
This action was still using Octokit, now it uses our API
## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)  
- [x] New feature (non-breaking change which adds functionality)  
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)  
- [ ] Documentation update  
- [x] Chore: cleanup/renaming, etc  
- [ ] RFC  
## Acceptance

- [ ] I have read [the Contributing guidelines](CONTRIBUTING.md)
- [ ] I have read the [Code of Conduct](CODE_OF_CONDUCT.md)

### CODE REVIEW

**Review by baristaGeek — COMMENTED** [review]
Not sure if this is the main goal of this PR or not, but doesn't fix the error I get. 

Screen Shot 2022-11-18 at 4 28 59 PM

**Comment by EstebanDalelR** [comment]
> Not sure if this is the main goal of this PR or not, but doesn't fix the error I get.
> 
> Screen Shot 2022-11-18 at 4 28 59 PM

No, unrelated.
Your dev environment is broken.

**Comment by EstebanDalelR** [comment]
> > Not sure if this is the main goal of this PR or not, but doesn't fix the error I get.
> > Screen Shot 2022-11-18 at 4 28 59 PM
> 
> No, unrelated. Your dev environment is broken.

As you can see in the code, @baristaGeek, this PR makes a request to our backend to start a repo when the button is clicked.

**Comment by EstebanDalelR** [comment]
Any updates @baristaGeek

**Pull request merged**
