### PR TITLE
Feature/track all links

### PR DESCRIPTION
**Pull request by EstebanDalelR**
## Description
This will track all links inside the webview.
## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)  
- [x] New feature (non-breaking change which adds functionality)  
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)  
- [ ] Documentation update  
- [ ] Chore: cleanup/renaming, etc  
- [ ] RFC  
## Acceptance

- [x] I have read [the Contributing guidelines](CONTRIBUTING.md)
- [x] I have read the [Code of Conduct](CODE_OF_CONDUCT.md)

### CODE REVIEW

**Review by baristaGeek — COMMENTED** [review]
Not sure if this is the main goal of this PR or not, but doesn't fix the error I get. 
Screen Shot 2022-11-18 at 4 28 59 PM

**Comment by EstebanDalelR** [comment]
> Not sure if this is the main goal of this PR or not, but doesn't fix the error I get. Screen Shot 2022-11-18 at 4 28 59 PM

No, unrelated.
Your dev environment is broken.

**Comment by EstebanDalelR** [comment]
> > Not sure if this is the main goal of this PR or not, but doesn't fix the error I get. Screen Shot 2022-11-18 at 4 28 59 PM
> 
> No, unrelated. Your dev environment is broken.

As you can see in the code, @baristaGeek, this PR creates a function that finds all links and onClick sends a telemetry event.

**Comment by EstebanDalelR** [comment]
Any updates @baristaGeek ?

**Pull request merged**
