### PR TITLE
Feature/treeview

### PR DESCRIPTION
**Pull request by EstebanDalelR**
## Description
Changes from webview to treeview.
We will use more VSCode APIs to improve reliability.
## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)  
- [x] New feature (non-breaking change which adds functionality)  
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)  
- [ ] Documentation update  
- [ ] Chore: cleanup/renaming, etc  
- [ ] RFC  
## Notes

Screenshot 2023-01-18 at 9 34 41 AM

## Acceptance

- [x] I have read [the Contributing guidelines](CONTRIBUTING.md)
- [x] I have read the [Code of Conduct](CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by baristaGeek** [comment]
Let's add instructions on our sidebar webview on how to run Watermelon. Something very basic, the soon to be hired freelanced product designer can help us do something very good. GitLens is a good example. 

Screen Shot 2023-01-18 at 11 21 54 AM

**Comment by baristaGeek** [comment]
> Should we remove the Watermelon logo from the treeview so that the get code context button becomes more visible?
> 
> Screen Shot 2023-01-18 at 11 33 21 AM

In fact, my suggestion is to simply leave the get code context button. The logo, the "star us on github" text can all go on the sidebar webview

**Comment by baristaGeek** [comment]
How will the [different pieces of information ](https://www.figma.com/file/qZ3AAEEVYlyQx07ktCSqJb/Untitled?node-id=0%3A1&t=6TNH4RkAACU3ayyJ-0)be presented with this new UI? Will everything be a treeview of a treeview? Does it deserve an RFC? Perhaps a few Figma mock-ups?

**Comment by baristaGeek** [comment]
Overall it's a good start for our v2 which will be epic. At the moment I have a few suggestions, and even more questions.

**Comment by EstebanDalelR** [comment]
> Let's add instructions on our sidebar webview on how to run Watermelon. Something very basic, the soon to be hired freelanced product designer can help us do something very good later. GitLens is a good example.
> 
> Screen Shot 2023-01-18 at 11 21 54 AM

Interesting, sounds like a Growth team task. 
We've had a welcome view for a long while that has had no updates since I wrote it.

**Comment by EstebanDalelR** [comment]
> > Should we remove the Watermelon logo from the treeview so that the get code context button becomes more visible?
> 
> > 
> 
> > Screen Shot 2023-01-18 at 11 33 21 AM
> 
> 
> 
> In fact, my suggestion is to simply leave the get code context button. The logo, the "star us on github" text can all go on the sidebar webview

Removed the whole we view.

**Comment by baristaGeek** [comment]
> > Let's add instructions on our sidebar webview on how to run Watermelon. Something very basic, the soon to be hired freelanced product designer can help us do something very good later. GitLens is a good example.
> > Screen Shot 2023-01-18 at 11 21 54 AM
> 
> Interesting, sounds like a Growth team task. We've had a welcome view for a long while that has had no updates since I wrote it.

Sure! But let's start with a simple text and then upgrade.

**Comment by baristaGeek** [comment]
This treeview looks great

Screen Shot 2023-01-19 at 5 58 00 PM

**Comment by baristaGeek** [comment]
I suspect that a lot of people will do something similar to this because the treeview is not easy to find at a glance. How can we tackle this?

https://user-images.githubusercontent.com/8325094/213581338-6e58b419-0164-4c4c-a388-87d57756c498.mov

**Comment by baristaGeek** [comment]
I deleted some comments that would be misguiding for the context of this PR. 

As discussed on Zoom, this is almost ready: Once we map to PR/tickets/threads title and links, we're ready.

**Review by baristaGeek — APPROVED** [review]

**Pull request merged**
